In [1]:
l = [1,2,3,5,'hello','yo',34]

In [2]:
l.remove('hello')

In [3]:
l

[1, 2, 3, 5, 'yo', 34]

In [4]:
l.pop(2)
l

[1, 2, 5, 'yo', 34]

In [5]:
del l[0]
l

[2, 5, 'yo', 34]

In [6]:
dict1 = {'a':'alpha','b':'beta','c':'gamma'}
dict1.items()

dict_items([('a', 'alpha'), ('b', 'beta'), ('c', 'gamma')])

In [30]:
l = []
for i in dict1.keys():
    l.append(i)
    l.append(dict1[i])
l

['a', 'alpha', 'b', 'beta', 'c', 'gamma']

In [31]:
l = []                         #IMPORTANT
for i in dict1.items():
    l.extend(i)
l

['a', 'alpha', 'b', 'beta', 'c', 'gamma']

In [32]:
l = []
for i,j in dict1.items():
    l.append(i)
    l.append(j)
l

['a', 'alpha', 'b', 'beta', 'c', 'gamma']

In [33]:
print("mumbai"+"is good")

mumbaiis good


In [34]:
print("mumbai","is good")

mumbai is good


In [39]:
import numpy as np
a = np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [40]:
a[::-1,::-1]

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

In [42]:
a.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [43]:
#But a[::-1,::-1] and a.T is different

In [45]:
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
b.mean(0)  #vertical mean

array([4., 5., 6.])

In [58]:
b.mean(1)  #horizontal mean

array([2., 5., 8.])

In [59]:
b.mean()

5.0

In [60]:
b.sum()

45

In [61]:
b.sum(0) #Vertical

array([12, 15, 18])

In [62]:
b.sum(1)  #horizontal

array([ 6, 15, 24])

In [86]:
#WHERE
a = np.array([1,2,3,4])
b = np.array([100,200,300,400])
c = np.array([True,False,True,False])
np.all(c)

False

In [87]:
np.any(c)

True

In [88]:
np.any(a>3)

True

In [89]:
np.all(a>3)

False

In [90]:
np.any(a>b)

False

In [91]:
np.any(b>a)

True

In [94]:
np.where(c,a,b)   #(condition,true,false)   so Trues in a were printed and Falses in b were printed(index wise)

array([  1, 200,   3, 400])

In [97]:
a = np.random.randint(1,101,10)
a

array([37, 65, 40, 36, 56, 70, 90,  2, 99, 54])

In [99]:
np.where(a<40)

(array([0, 3, 7], dtype=int64),)

In [102]:
#in array/series if even one value is null, the entire thing is converted to float

In [103]:
#For pulling data from Series:
#1: By index
#2: By label
#3: By mutiple labels a[['A','B']]
#4: By range a[0:3]
#5 By logic a[a<3]

#For data Frame:
#labels
#multiple labels
#df[0:2] first two rows
#logic(such as Sachin rows)
#iloc[rows,columns]
#loc[labels]

In [109]:
import pandas as pd
from pandas import Series, DataFrame
ser1 = Series(data=['India','Bhutan','Nepal'],index=[1,5,10])
ser1

1      India
5     Bhutan
10     Nepal
dtype: object

In [122]:
s = ser1.reindex(range(12))

In [123]:
ser1.reindex(range(12),method='ffill')

0        NaN
1      India
2      India
3      India
4      India
5     Bhutan
6     Bhutan
7     Bhutan
8     Bhutan
9     Bhutan
10     Nepal
11     Nepal
dtype: object

In [124]:
ser1.reindex(range(12),method='bfill')

0      India
1      India
2     Bhutan
3     Bhutan
4     Bhutan
5     Bhutan
6      Nepal
7      Nepal
8      Nepal
9      Nepal
10     Nepal
11       NaN
dtype: object

In [125]:
ser1.reindex(range(12),method='nearest')

0      India
1      India
2      India
3     Bhutan
4     Bhutan
5     Bhutan
6     Bhutan
7     Bhutan
8      Nepal
9      Nepal
10     Nepal
11     Nepal
dtype: object

In [126]:
s

0        NaN
1      India
2        NaN
3        NaN
4        NaN
5     Bhutan
6        NaN
7        NaN
8        NaN
9        NaN
10     Nepal
11       NaN
dtype: object

In [129]:
s.fillna('Pak')

0        Pak
1      India
2        Pak
3        Pak
4        Pak
5     Bhutan
6        Pak
7        Pak
8        Pak
9        Pak
10     Nepal
11       Pak
dtype: object

In [130]:
s.fillna(method='ffill')

0        NaN
1      India
2      India
3      India
4      India
5     Bhutan
6     Bhutan
7     Bhutan
8     Bhutan
9     Bhutan
10     Nepal
11     Nepal
dtype: object

In [131]:
s.fillna(method='bfill')

0      India
1      India
2     Bhutan
3     Bhutan
4     Bhutan
5     Bhutan
6      Nepal
7      Nepal
8      Nepal
9      Nepal
10     Nepal
11       NaN
dtype: object

In [ ]:
#covariance 0 means not related
#higher covariance means more related data
#how two data vary togther, is what covariance tells
#Summation(x-xbar)(y-ybar)/N